# Generated by Django 3.0.8 on 2020-08-10 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('ip_track_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=50)),
                ('track_name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('creater', models.GenericIPAddressField(default='0.0.0.0')),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinates_id', models.AutoField(primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Track')),
            ],
        ),
    ]
