# Generated by Django 3.0.8 on 2020-07-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
