# Generated by Django 3.1 on 2020-08-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='creater',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
