# Generated by Django 3.1 on 2020-08-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
