# Generated by Django 3.1 on 2020-08-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_track_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='modified_time',
            field=models.TimeField(),
        ),
    ]
