# Generated by Django 3.0.8 on 2020-08-05 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20200731_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinates_id', models.AutoField(primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=50)),
                ('strat', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Track')),
            ],
        ),
    ]
