# Generated by Django 3.1 on 2020-08-23 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20200823_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
