# Generated by Django 3.0.8 on 2020-08-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_auto_20200805_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='strat',
            new_name='start',
        ),
    ]
